name = "synpixel/chrome"
version = "0.2.5"
description = "A port of rust-headless-chrome to Luau, built for Lune"
authors = ["synpixel"]
license = "MIT"
repository = "https://github.com/synpixel/chrome.luau"
includes = ["pesde.toml", "README.md", "LICENSE", "docs", "src"]

[target]
environment = "lune"
lib = "src/init.luau"

[scripts]
build = "scripts/build.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"
